### ISSUE TITLE
Missing Events in Issue/PR view

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/Freetime#152]
- [ ] ~~"Duplicate of" as seen in #150~~
- [ ] ~~"Deleted Comment" as seen in #146~~
- [ ] "Added to milestone" as seen in #27 
- [ ] "Removed from milestone"
- [x] "X referenced this issue" as also seen in #27

**Comment by rnystrom** [comment]
Last one is already built but the API is having issues, see #55

**Comment by rnystrom** [comment]
Deleted comment doesn't exist in the [timeline API](https://developer.github.com/v4/reference/union/pullrequesttimelineitem/), removed.

**Comment by rnystrom** [comment]
Same w/ duplicates
